apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: odh-applications
namePrefix: data-science-pipelines-operator-
resources:
  - ../crd
  - ../rbac
  - ../manager
  - ../prometheus
  - ../configmaps

# Parameterize images via KfDef in ODH
configMapGenerator:
  - name: dspo-parameters
    envs:
      - params.env
vars:
  - name: IMAGES_APISERVER
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGES_APISERVER
  - name: IMAGES_ARTIFACT
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGES_ARTIFACT
  - name: IMAGES_OAUTHPROXY
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGES_OAUTHPROXY
  - name: IMAGES_PERSISTENTAGENT
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGES_PERSISTENTAGENT
  - name: IMAGES_SCHEDULEDWORKFLOW
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGES_SCHEDULEDWORKFLOW
  - name: IMAGES_CACHE
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGES_CACHE
  - name: IMAGES_MOVERESULTSIMAGE
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGES_MOVERESULTSIMAGE
  - name: IMAGES_MARIADB
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGES_MARIADB
  - name: IMAGES_MLMDENVOY
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGES_MLMDENVOY
  - name: IMAGES_MLMDGRPC
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGES_MLMDGRPC
  - name: IMAGES_MLMDWRITER
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGES_MLMDWRITER
  - name: IMAGES_CRDVIEWER
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGES_CRDVIEWER
  - name: IMAGES_VISUALIZATIONSERVER
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGES_VISUALIZATIONSERVER
  - name: IMAGES_DSPO
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGES_DSPO
  - name: ZAP_LOG_LEVEL
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.ZAP_LOG_LEVEL
  - name: IMAGESV2_ARGO_APISERVER
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGESV2_ARGO_APISERVER
  - name: IMAGESV2_ARGO_ARTIFACT
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGESV2_ARGO_ARTIFACT
  - name: IMAGESV2_ARGO_PERSISTENTAGENT
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGESV2_ARGO_PERSISTENTAGENT
  - name: IMAGESV2_ARGO_SCHEDULEDWORKFLOW
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGESV2_ARGO_SCHEDULEDWORKFLOW
  - name: IMAGESV2_ARGO_CACHE
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGESV2_ARGO_CACHE
  - name: IMAGESV2_ARGO_MOVERESULTSIMAGE
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGESV2_ARGO_MOVERESULTSIMAGE
  - name: IMAGESV2_ARGO_MLMDENVOY
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGESV2_ARGO_MLMDENVOY
  - name: IMAGESV2_ARGO_MLMDGRPC
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGESV2_ARGO_MLMDGRPC
  - name: IMAGESV2_ARGO_MLMDWRITER
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGESV2_ARGO_MLMDWRITER
  - name: IMAGESV2_ARGO_VISUALIZATIONSERVER
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGESV2_ARGO_VISUALIZATIONSERVER
  - name: IMAGESV2_ARGO_WORKFLOWCONTROLLER
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGESV2_ARGO_WORKFLOWCONTROLLER
  - name: IMAGESV2_TEKTON_APISERVER
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGESV2_TEKTON_APISERVER
  - name: IMAGESV2_TEKTON_ARTIFACT
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGESV2_TEKTON_ARTIFACT
  - name: IMAGESV2_TEKTON_PERSISTENTAGENT
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGESV2_TEKTON_PERSISTENTAGENT
  - name: IMAGESV2_TEKTON_SCHEDULEDWORKFLOW
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGESV2_TEKTON_SCHEDULEDWORKFLOW
  - name: IMAGESV2_TEKTON_CACHE
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGESV2_TEKTON_CACHE
  - name: IMAGESV2_TEKTON_MOVERESULTSIMAGE
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGESV2_TEKTON_MOVERESULTSIMAGE
  - name: IMAGESV2_TEKTON_MLMDENVOY
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGESV2_TEKTON_MLMDENVOY
  - name: IMAGESV2_TEKTON_MLMDGRPC
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGESV2_TEKTON_MLMDGRPC
  - name: IMAGESV2_TEKTON_MLMDWRITER
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGESV2_TEKTON_MLMDWRITER
  - name: IMAGESV2_TEKTON_VISUALIZATIONSERVER
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGESV2_TEKTON_VISUALIZATIONSERVER
  - name: IMAGESV2_TEKTON_WORKFLOWCONTROLLER
    objref:
      kind: ConfigMap
      name: dspo-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGESV2_TEKTON_WORKFLOWCONTROLLER
configurations:
  - params.yaml
