apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: test-mariadb
  labels:
    app: mariadb
    component: data-science-pipelines
spec:
  strategy:
    type: Recreate  # Need this since backing PVC is ReadWriteOnce, which creates resource lock condition in default Rolling strategy
  selector:
    matchLabels:
      app: mariadb
      component: data-science-pipelines
  template:
    metadata:
      labels:
        app: mariadb
        component: data-science-pipelines
    spec:
      containers:
        - name: mariadb
          image: quay.io/centos7/mariadb-103-centos7:ea07c0dade9571d78a272b453fd2dea92077dc7f
          ports:
            - containerPort: 3306
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - "-i"
                - "-c"
                - >-
                  MYSQL_PWD=$MYSQL_PASSWORD mysql -h 127.0.0.1 -u $MYSQL_USER -D
                  $MYSQL_DATABASE -e 'SELECT 1'
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          env:
            - name: MYSQL_USER
              value: "mlpipeline"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: "password"
                  name: "ds-pipeline-db-test"
            - name: MYSQL_DATABASE
              value: "mlpipeline"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
          resources:
            limits:
              cpu: 20m
              memory: 500Mi
            requests:
              cpu: 20m
              memory: 100m
          volumeMounts:
            - name: mariadb-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-test
