kind: Secret
apiVersion: v1
metadata:
  name: ds-pipeline-db-test
  namespace: test-mariadb
  labels:
    app: mariadb
    component: data-science-pipelines
stringData:
  password: password
type: Opaque
